name: Upstream Sync - Smart Mermaid

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *" # 定时触发器：每天 UTC 时间 4:00 (北京时间中午 12:00) 运行一次
  workflow_dispatch: # 允许手动从 GitHub Actions 页面触发此工作流

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from smart-mermaid/smart-mermaid
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 确保只在 Fork 仓库中运行

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: smart-mermaid/smart-mermaid # *** 这里是上游仓库的完整路径 ***
          upstream_sync_branch: main # *** 这里是上游仓库要同步的分支 (通常是 main 或 master) ***
          target_sync_branch: main # *** 这里是你的 Fork 仓库要同步的分支 (通常是 main 或 master) ***
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的默认 Token

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1
